spring:
  application:
    name: flight-search-api

server:
  port: 8080

currency:
  conversion:
    enable: true
    offline: true
    rates-date: "2025-01-10"
    supported-currencies:
      - USD
      - EUR
      - MXN

amadeus:
  api:
    base-url: https://test.api.amadeus.com
    base-url-v1: ${amadeus.api.base-url}/v1
    base-url-v2: ${amadeus.api.base-url}/v2
    auth-url: ${amadeus.api.base-url}/v1/security/oauth2/token
    key: ${AMADEUS_API_SECRET} #Change this wiht your own API Key
    secret: ${AMADEUS_API_SECRET} #CHange this wiht your own API secret
  token:
    expiry-buffer: 300

logging:
  level:
    root: INFO
    com.FlightSearch.breakabletoy2: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
