spring:
  application:
    name: flight-search-api

server:
  port: 8080

amadeus:
  api:
    base-url: https://test.api.amadeus.com
    auth-url: ${amadeus.api.base-url}/v1/security/oauth2/token
    key: ${AMADEUS_API_SECRET} #Change this wiht your own API Key
    secret: ${AMADEUS_API_SECRET} #CHange this wiht your own API secret
  token:
    expiry-buffer: 300

logging:
  level:
    com.FlightSearch.breakabletoy2: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.client.HttpMessageConverterExtractor: TRACE